apiVersion: pulsar.monime.sl/v1alpha1
kind: PulsarCluster
metadata:
  name: cluster-1
  namespace: pulsar
spec:
  size: 3
  zookeeperServers: "cluster-1-zk-headless.zookeeper.svc.cluster.local:2181"
  bookkeeperClusterUri: "zk://cluster-1-zk-headless.zookeeper.svc.cluster.local:2181/bookkeeper/cluster-1/ledgers"
  jvmOptions:
    memory:
      - "-Xms128m"
      - "-Xmx256m"
      - "-XX:MaxDirectMemorySize=256m"
  connectors:
    builtin:
      - "aerospike"